version: "2"
linters:
  default: standard
  disable:
    - errcheck
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
issues:
  option: value
output:
  option: value
run:
  option: value
severity:
  option: value
