reqs:
  update_req_type : "request.form.update"
  create_req_type : "request.form.create"
  delete_req_type : "request.form.delete"
rabbitmq_url : "amqp://rabbitmq:5672"
input_queue_name : "votes"
req_queue_name : "requests"
req_exchange : "requests"
out_exchange : "votes"
