reqs:
  update_req_type: "request.form.update"
  create_req_type: "request.form.create"
  delete_req_type: "request.form.delete"
urls:
  redis: "redis:6379"
  rabbbitmq: "amqp://rabbitmq:5672"
exchange:
  request: "request"
  output: "output"
queue:
  request: "request"
  output: "output"
health:
  port: 8080
  use: true